#!/usr/bin/env node
// Writes a real HTML file for every route, so deep links on GitHub Pages
// return 200 with the right title, description and canonical baked in,
// instead of the 404.html fallback (which Google will not index). Routes
// marked prerender: true also get their page rendered into #app, so the
// articles are in the HTML for crawlers, link previews and anyone with
// JavaScript off; bas morphs over the same markup when it boots. Also writes
// 404.html itself, sitemap.xml and robots.txt.
//
// k/index.html is the template and k/js/routes.js is the route table. It is
// the same table the browser uses, imported as is, so there is nothing to
// keep in step by hand. Run this after adding an article or a route:
//
//     node tools/build_routes.mjs
//
// No dependencies, no node_modules. Idempotent.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { routes, options } from '../k/js/routes.js';
import { prerender, staticPaths } from '../k/js/framework.js';
import { getArticle } from '../k/js/pages/articles/articles-data.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const K = join(ROOT, 'k');
const SITE = options.origin;
const TEMPLATE = (await readFile(join(K, 'index.html'), 'utf8')).replace(/\r\n/g, '\n');

// ── templating ──────────────────────────────────────────────────────────

const esc = s => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// exactly one match or it throws: a template edit should fail loudly, not quietly skip a tag
function sub(html, pattern, replacement) {
    let n = 0;
    const out = html.replace(pattern, (...m) => { n++; return replacement(...m); });
    if (n !== 1) throw new Error(`${n} matches for ${pattern}`);
    return out;
}
const attr = (html, pattern, value) => sub(html, pattern, (m, open, close) => open + value + close);

const BANNER = '<!-- GENERATED by tools/build_routes.mjs from k/index.html. Do not edit; '
    + 'edit the template and rerun the script. This file exists so GitHub Pages '
    + 'serves this route with a 200 and its own title, social tags and content. -->\n';

function shell({ head, url, html, params }) {
    let out = TEMPLATE.replace('<!DOCTYPE html>\n', () => '<!DOCTYPE html>\n' + BANNER);
    out = sub(out, /<title>[\s\S]*?<\/title>/, () => `<title>${esc(head.title)}</title>`);
    out = attr(out, /(<meta name="description" content=")[^"]*(")/, esc(head.description));
    out = attr(out, /(<link rel="canonical" href=")[^"]*(")/, url);
    out = attr(out, /(<meta property="og:title" content=")[^"]*(")/, esc(head.title));
    out = attr(out, /(<meta property="og:description" content=")[^"]*(")/, esc(head.description));
    out = attr(out, /(<meta property="og:url" content=")[^"]*(")/, url);
    out = attr(out, /(<meta property="og:type" content=")[^"]*(")/, head.type || 'website');
    out = attr(out, /(<meta name="twitter:title" content=")[^"]*(")/, esc(head.title));
    out = attr(out, /(<meta name="twitter:description" content=")[^"]*(")/, esc(head.description));
    if (head.noindex) out = attr(out, /(<meta name="robots" content=")[^"]*(")/, 'noindex, follow');

    const article = head.type === 'article' && getArticle(params.slug);
    if (article) {
        const ld = JSON.stringify({
            '@context': 'https://schema.org', '@type': 'Article',
            headline: article.title, description: head.description, url,
            author: { '@type': 'Person', name: 'Prateek Kumar Gupta', url: `${SITE}/k/` },
            image: `${SITE}/k/media/og.jpg`, inLanguage: 'en-GB',
        }).replace(/</g, '\\u003c');
        out = sub(out, /\n\s*<!-- route-schema -->/, () => `\n    <script type="application/ld+json">${ld}</script>`);
    }

    if (html != null) {
        // the page itself, where bas will render it; the "needs JavaScript" note no longer applies
        out = sub(out, /<div id="app"><\/div>/, () => `<div id="app">${html}</div>`);
        out = sub(out, /\n\s*<noscript>[\s\S]*?<\/noscript>/, () => '');
    }
    return out;
}

// ── outputs ─────────────────────────────────────────────────────────────

const written = [];
async function write(file, text) {
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, text, 'utf8');
    written.push(relative(ROOT, file).replace(/\\/g, '/'));
}

// the home page is the template itself, so it is the one path with no file to write
const home = await prerender(routes, '/', options);
const templateTitle = TEMPLATE.match(/<title>([\s\S]*?)<\/title>/)[1];
if (templateTitle !== esc(home.head.title)) {
    console.warn(`! the home title in k/js/routes.js and k/index.html differ:\n    ${home.head.title}\n    ${templateTitle}`);
}

const pages = [];
for (const path of staticPaths(routes).filter(p => p !== '/')) {
    const page = await prerender(routes, path, options);
    if (page.notFound) throw new Error(`${path} is listed by a route but matches none`);
    pages.push(page);
    await write(join(K, path, 'index.html'), shell(page));
}

// 404.html: the home shell, marked noindex; it only exists so unknown URLs still boot the app
await write(join(ROOT, '404.html'), shell({ ...home, head: { ...home.head, noindex: true } }));

const today = new Date().toISOString().slice(0, 10);
const priority = p => p.path === '/' ? '1.0' : p.head.type === 'article' ? '0.8' : '0.6';
const sitemap = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...[home, ...pages].filter(p => !p.head.noindex).map(p =>
        `  <url><loc>${p.url}</loc><lastmod>${today}</lastmod><priority>${priority(p)}</priority></url>`),
    '</urlset>'];
await write(join(ROOT, 'sitemap.xml'), sitemap.join('\n') + '\n');
await write(join(ROOT, 'robots.txt'), `User-agent: *\nAllow: /\nDisallow: /k/test\n\nSitemap: ${SITE}/sitemap.xml\n`);

console.log(`${pages.length} routes, ${pages.filter(p => p.html != null).length} with their content baked in`);
for (const w of written) console.log('  wrote', w);
